### ISSUE TITLE
Switching order of players bug.

### ISSUE THREAD

**Issue by alexjmak** [malikh22/ShogiCS301#6]
(Minor / Other) If I switch the order of players such that the first player is the Dumb Computer Player and the second player is the Human player, I cannot make moves.

**Comment by faker20** [comment]
Issue caused by legalMoveList restriction. Only run when playerNum is 0. Now fixed.

**Comment by malikh22** [comment]
Not entirely fixed. Just recommend always playing as Player 0 (see game manual)

**Comment by alexjmak** [comment]
Ok, thanks for the update.
